### ISSUE TITLE
你好！请问可以分享一下best_model.weights 文件吗？

### ISSUE THREAD

**Issue by zihaowwng** [jackie930/t5-pegasus-textsummary#2]

**Comment by jackie930** [comment]
您好 可以通过这个路径下载: ( 7day valid)
链接: https://pan.baidu.com/s/1Z07j-HIGaCCvS32mQE2LwQ  密码: 6fg4

**Comment by zihaowwng** [comment]
> 您好 可以通过这个路径下载: ( 7day valid) 链接: https://pan.baidu.com/s/1Z07j-HIGaCCvS32mQE2LwQ 密码: 6fg4

十分感谢！
